apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
  namespace: microservices
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: 'driss123'
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eureka-server:8761/eureka/'