# car/src/main/resources/application.yml
server:
  port: 8082

spring:
  application:
    name: car-service
  cloud:
    kubernetes:
      enabled: true
      config:
        enabled: true
      discovery:
        enabled: true
    discovery:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-service.microservices.svc.cluster.local:3306/carservicedb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: driss123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # Updated dialect
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false