# k8s/deployments/client-service-deployment.yaml (remove the check-eureka container)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-service
  template:
    metadata:
      labels:
        app: client-service
    spec:
      serviceAccountName: spring-cloud-kubernetes
      initContainers:
        - name: check-mysql
          image: busybox:1.28
          command: ['sh', '-c',
                    'until nc -z mysql-service.microservices.svc.cluster.local 3306; do echo waiting for mysql; sleep 2; done;']
      containers:
        - name: client-service
          image: docker.io/drisszamanii/client-service:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: SPRING_APPLICATION_NAME
              value: "client-service"
            - name: SERVER_PORT
              value: "8081"