pipeline {
    agent any

    tools {
        jdk 'JDK 17'
        maven 'Maven_3.9.9'
    }

    stages {
        stage('Test') {
            steps {
                dir('car') {
                    sh 'mvn clean test -Dspring.profiles.active=test -B'
                }
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }
    }
}