#client-service(application.yml)
server:
  port: 8081

spring:
  application:
    name: client-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/clientservicedb
    username: root
    password: driss123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:mysql://mysql-service.microservices.svc.cluster.local:3306/clientservicedb
    username: root
    password: driss123
  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true
      reload:
        enabled: true

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://eureka-service.microservices.svc.cluster.local:8761/eureka/
  instance:
    preferIpAddress: true