server:
  port: 8081
spring:
  application:
    name: SERVICE-CLIENT
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-service:3306/clientservicedb
    username: root
    password: driss123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  cloud:
    kubernetes:
      discovery:
        enabled: false  # Changed to false since we're using Eureka
      config:
        enabled: true
      reload:
        enabled: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    preferIpAddress: true