apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-cloud-kubernetes-binding
  namespace: microservices
subjects:
  - kind: ServiceAccount
    name: spring-cloud-kubernetes
    namespace: microservices
roleRef:
  kind: Role
  name: spring-cloud-kubernetes-role
  apiGroup: rbac.authorization.k8s.io