apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: microservices
spec:
  selector:
    app: client-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP