apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: microservices  # Add this
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-service.microservices.svc.cluster.local:8761/eureka/"  # Update this
  SPRING_PROFILES_ACTIVE: "prod"