apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
  namespace: microservices
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS carservicedb;
    CREATE DATABASE IF NOT EXISTS clientservicedb;
    USE carservicedb;
    CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'driss123';
    GRANT ALL PRIVILEGES ON . TO 'root'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;