apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
  namespace: microservices
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS carservicedb;
    CREATE DATABASE IF NOT EXISTS clientservicedb;