apiVersion: v1
kind: ConfigMap
metadata:
  name: service-discovery-config
  namespace: microservices
data:
  spring.cloud.kubernetes.discovery.enabled: "false"
  eureka.client.serviceUrl.defaultZone: "http://eureka-service:8761/eureka/"
  eureka.instance.preferIpAddress: "true"
  eureka.client.register-with-eureka: "true"
  eureka.client.fetch-registry: "true"